### PR TITLE
Analytics Frontend changes

### PR DESCRIPTION
**Pull request by CytexalMika**
Changes for submitting analytics from the frontend to the backend.

### CODE REVIEW

**Review by LennartCode — CHANGES_REQUESTED** [review]
The class "AnalyticsSettings" is unknown, probably a missing file.

**Comment by CytexalMika** [comment]
> The class "AnalyticsSettings" is unknown, probably a missing file.

Fixed!

**Review by LennartCode — APPROVED** [review]
LGTM

**Comment by LennartCode** [comment]
Sorry for the messed up order. The GitHub CLI and UI behave inconsisently.

**Pull request merged**
